### ISSUE TITLE
Words that start with a number throw an exception

### ISSUE THREAD

**Issue by jeroenbourgois** [yohang88/letter-avatar#1]
Hi

When trying combinations where the first word is a number, an exception is thrown. In my app I bypass this now by stripping numbers altogether but I was wondering what your approach would be. Should the package support numbers or strip them? If you want I can make a PR for a proposed strategy!

**Comment by yohangdev** [comment]
@jeroenbourgois yes, that's was known error for long time 😁  also for non-alphabet names, etc. If you have a time for making PR fix, it's great. Thank you so much.
