### ISSUE TITLE
Save avatar into file

### ISSUE THREAD

**Issue by virtoso** [yohang88/letter-avatar#8]
Hi! Can you add method which save avatar in the file?

Smth like that:
`public method saveAs($name, $extension = '.png')`

**Comment by ridaamirini** [comment]
[`Commit Added saveAs Method`](https://github.com/ridaamirini/letter-avatar/commit/9081b726a00feb8e19a5c317eca9716c61e6c1fa)

like this?

**Comment by virtoso** [comment]
Yep. That will be very helpful :+1:
